services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      SAFECART_ENV: development
      SAFECART_DATA_PATH: /data/bpom
      SAFECART_LOG_LEVEL: INFO
    volumes:
      - ../dataset/Data BPOM:/data/bpom:ro

